### ISSUE TITLE
Horse Racing Assignment 

### ISSUE THREAD

**Issue by CodingMasterDaniel** [CodingMasterDaniel/ICS3U#4]
Hello Mr. DesLauriers,

My Horse Racing Assignment is done and ready to be marked. 
My additional functions are: 
1. Any name can be chosen by both the index or the name in text
2. A player can bet on multiple horses as long as he/she has money

Thank you,
Daniel Yan

**Comment by kevindeslauriers** [comment]
Excellent Work Daniel.  

Comments: You should not allow user to be (or choose to bet) if they have no $$. You did not supply input files - I had to make my own. Some of your methods used an incorrect naming convention - ChooseHorse should be chooseHorse.

y is an option for yes and you did not handle this.

When writing to a file - it seemed to write it all on one line - in notepad.  But works in Eclipse.

98%
